USE `google_auth`;

DROP TABLE IF EXISTS Game;
CREATE TABLE IF NOT EXISTS Game (
`gameId` BIGINT(20) NOT NULL AUTO_INCREMENT,
`gameName` VARCHAR(30) NOT NULL ,
`createdDate` DATETIME NOT NULL ,
PRIMARY KEY (`gameId`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

